version: 2
jobs:
  build:    
    docker:
      - image: cirrusci/flutter:latest

    branches:
      only: master

    steps:
      - checkout:
          path: reviewapp

      - run:
          name: Run Flutter doctor
          command: flutter doctor

      - run:
          name: Run the application tests
          command: flutter test
          path: reviewapp

      - run:
          name: Build the Android version
          command: flutter build apk 
          path: reviewapp

      - store_artifacts:
          path: build/app/outputs/apk/release/reviewapp-release.apk
  