name: mdns_plugin
description: 
  mDNS Service discovery plugin for iOS which generates events 
  whenever service discovery is started or stopped, or whenever
  new services on the network are found, removed or updated.
version: 0.0.5
author: David Thorpe <djt@mutablelogic.com>
homepage: https://github.com/djthorpe/flutter/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.mutablelogic.mdns_plugin
    pluginClass: MDNSPlugin
