version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter:latest

    branches:
      only: master

    steps:
      - checkout

      - run:
          name: Flutter Doctor
          command: flutter doctor

      - run:
          name: Install Protocol Buffers
          command: |
            cd ~/sdks
            wget https://github.com/protocolbuffers/protobuf/releases/download/v3.9.2/protoc-3.9.2-linux-x86_64.zip
            install -d protoc
            cd protoc && unzip ../protoc-3.9.2-linux-x86_64.zip
            flutter pub global activate protoc_plugin

      - run:
          name: Generate Dart gRPC files
          environment:
            PATH: $PATH:$HOME/sdks/protoc/bin:$HOME/.pub-cache/bin
          command: |            
            cd ~/project/grpc_client
            echo $PATH
            /usr/bin/install -d lib/providers/google/protobuf
            /usr/bin/install -d lib/providers/grpc/reflection/v1alpha
            chmod +x ${HOME}/project/genproto-circleci.sh
            ${HOME}/project/genproto-circleci.sh

      - run:
          name: Test
          environment:
            PATH: $PATH:$HOME/sdks/protoc/bin:$HOME/.pub-cache/bin
          command: |
            cd ~/project/reviewapp && flutter test
            cd ~/project/mdns_browser && flutter test
            cd ~/project/grpc_client && flutter test

      - run:
          name: Build Android APKs
          environment:
            PATH: $PATH:$HOME/sdks/protoc/bin:$HOME/.pub-cache/bin
          command: |
            cd ~/project/reviewapp && flutter build apk 
            cd ~/project/mdns_browser && flutter build apk
            cd ~/project/grpc_client && flutter build apk

      - store_artifacts:
          path: reviewapp/build/app/outputs/apk/release/app-release.apk

      - store_artifacts:
          path: mdns_browser/build/app/outputs/apk/release/app-release.apk

      - store_artifacts:
          path: grpc_client/build/app/outputs/apk/release/app-release.apk
