version: 2
jobs:
  build:    
    docker:
      - image: cirrusci/flutter:latest
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: Flutter doctor
          command: flutter doctor
      - run:
          name: Tests
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}/reviewapp && flutter test
            cd ${CIRCLE_WORKING_DIRECTORY}/mdns_browser && flutter test
      - run:
          name: Build Android APKs
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}/reviewapp && flutter build apk 
            cd ${CIRCLE_WORKING_DIRECTORY}/mdns_browser && flutter build apk
      - store_artifacts:
          path: reviewapp/build/app/outputs/apk/release/app-release.apk
      - store_artifacts:
          path: mdns_browser/build/app/outputs/apk/release/app-release.apk
